name: pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest", "lts/*"]

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6.0.3
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install and build
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
