name: pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  pipeline:
    name: pipeline
    environment: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4.3.0
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install and build
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          cd test && pnpm install --frozen-lockfile
          cd .. && pnpm test

      - name: Publish
        run: pnpm publish --no-git-checks --provenance --access public
